apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env-httpbin-app
spec:
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  project: dev-env-project
  source:
    path: apps/pattern3/dev-env/apps/httpbin-app
    repoURL: https://github.com/rcarrata/kcd23ams-gitops-patterns
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
