apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-env-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rcarrata/CdCon23-GitOpsMultiCluster.git
        revision: main
        directories:
          - path: apps/demo4/staging-env/apps/*
          - path: apps/demo4/staging-env/namespaces/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: staging-env-appset-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rcarrata/CdCon23-GitOpsMultiCluster.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
