apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-env-multicluster-app
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          prod: "true"
  template:
    metadata:
      name: "{{name}}-prod-env-awesome-app"
    spec:
      project: apps-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rcarrata/CdCon23-GitOpsMultiCluster.git
        targetRevision: main
        path: apps/demo4/demo5/prod-env/overlays
      destination:
        server: "{{server}}"
        namespace: welcome-app
