kind: Deployment
apiVersion: apps/v1
metadata:
  name: welcome-app
  namespace: welcome-app
  labels:
    app: welcome-app
    app.kubernetes.io/component: welcome-app
    app.kubernetes.io/instance: welcome-app
    app.kubernetes.io/name: welcome-app
    app.kubernetes.io/part-of: welcome-app-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: welcome-app
        deployment: welcome-app
    spec:
      containers:
        - name: welcome-app
          image: quay.io/redhatworkshops/welcome-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
