apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-gpu-

resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
  - replicas.yaml
  - version.yaml
