apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: integration
namePrefix: integration-gpu-

resources:
  - ../../base

components:
  - ../../variants/us

patchesStrategicMerge:
  - deployment.yaml
  - version.yaml
