---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  template:
    spec:
      containers:
        - name: welcome-app
          env:
            - name: REGION
              value: "us"
