apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project001

bases:
- ../baseline

patchesStrategicMerge:
- storage-class-quota.yaml

resources:
- namespace.yaml
- rolebinding.yaml
