apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-eu-

resources:
  - ../../base

components:
  - ../../variants/eu

patchesStrategicMerge:
  - deployment.yaml
  - version.yaml
