apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging-env-appset-project
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
